### PR TITLE
Added support for Cyclone to Snow

### PR DESCRIPTION
**Pull request by arthurmaciel**
Dear Alex, this a PR to add support for Cyclone (http://cyclone-scheme.org/) to Snow-Chibi. It works here, but of course please carefully review the modifications.

Do you plan to release a snow project independent of Chibi libs (maybe couting only on R7RS)?

Kind regards,
Arthur

### CODE REVIEW

**Comment by ashinn** [comment]
Thanks Arthur!

I've been gradually making all of the snow dependencies portable, and ultimately hope to put the snow client itself on snow-fort.org.  There's a lot of code, though, and much of it cannot be made portable, e.g. the http, filesystem and process interfaces.  The former two I've cond-expanded for Chicken, I'll probably cond-expand the rest of it eventually.

**Comment by arthurmaciel** [comment]
Thanks Alex for the quick merge and response! Good news to hear you plan to
release a portable snow into snow-fort.org. With it it would be much easier
to invest collective effort into a single application rather than spread
the effort into package managers per implementation. Congratulations for
this great initiative and for Chibi itself of course!

**Comment by arthurmaciel** [comment]
Dear Alex,

I'm still trying to make snow-chibi work with Cyclone scheme, but this
implementation only searches for files according to a library 'path'. I.e.
(cyclone iset base) will make the compiler search for
/tmp/pkg-XXX-XXX/cyclone/iset/base.sld/scm (and not for
/tmp/pkg-XXX-XXX/base.scm as snow-chibi currently does). I've been
re-reading the docs on packaging, but I cannot find a directive through
which I can instruct snow-chibi to create these subdirectories. Could you
help me please pointing out new docs I've been missing? Thanks!

Have a Happy New Year!

Cheers,
Arthur

**Comment by ashinn** [comment]
Are you having trouble building packages or installing them?

For installing, the package.scm will specify the path to the library file, so no search path is involved.

**Comment by arthurmaciel** [comment]
The problem is when building packages.

Em 12 de jan de 2018 22:45, "Alex Shinn" <notifications@github.com>
escreveu:

Are you having trouble building packages or installing them?

For installing, the package.scm will specify the path to the library file,
so no search path is involved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ashinn/chibi-scheme/pull/422#issuecomment-357394132>,
or mute the thread

**Comment by arthurmaciel** [comment]
Dear Alex, any news on how to snow-chibi to create subdirectories when building packages? Thanks!

**Comment by ashinn** [comment]
Hi Arthur,

I'm still not sure what the problem is.  The Makefile contains commands to build a number of packages (snowballs) at the very end, and these include .sld files in subdirectories which include .scm files from nested subdirectories.)  The nested structure is preserved in the tarball and in the path.

Could you give me an example directory structure and command where this is failing for you?  e.g. see the tests/snow directory.

**Pull request merged**
